language: objective-c
osx_image: xcode10.2

script:
- set -o pipefail && xcodebuild test -workspace device-kit.xcworkspace -scheme device-kit -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty

- xcodebuild -scheme device-kit -workspace device-kit.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.2' build test

after_success:
- bash <(curl -s https://codecov.io/bash)
