language: objective-c
osx_image: xcode10.1

script:
- set -o pipefail && xcodebuild test -project device-kit.xcodeproj -scheme device-kit -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty

- xcodebuild -scheme device-kit -project device-kit.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' build test

after_success:
- bash <(curl -s https://codecov.io/bash)
